import pandas as pd
import numpy as np

def cheese_brand_split():
    df = pd.read_csv('data/cheese_list.csv', encoding ='utf-8')
    # print(df)
    name = df['name'].str.split(']')
    df['brand'] = name.str.get(0)
    df['name'] = name.str.get(1)

    split = df['brand'].str.split('[')
    df['brand'] = split.str.get(1)

    # 열 순서 바꾸기
    # print(list(df))
    change_df_col = df[['brand', 'name', 'country', 'matching', 'texture', 'types', 'category', 'price', 'content', 'img']]
    print(change_df_col)

    # cols = df.columns.tolist()
    # cols = cols[-1:] + cols[:-1]

    # 공백 제거
    # brand = change_df_col['brand']
    # [i.replace(" ", "" ) for i in brand]
    # print(df)

    # df_cheese.to_csv("data/cheese_list2.csv")

cheese_brand_split()

'''
### after_df ###
     brand              name  ...                                   content                                                img
0     캐시밸리       미국 전통 치즈 5종  ...                           일상 속 가볍게 즐기는 치즈  https://img-cf.kurly.com/shop/data/goods/15647...
1      안젤로         고르곤졸라 피칸테  ...                          섹시한 이탈리아 대표 블루치즈  https://img-cf.kurly.com/shop/data/goods/15107...
2   라 콘타디나           버팔로 리코타  ...                   디저트 대신 떠먹고 싶은 구름을 닮은 치즈  https://img-cf.kurly.com/shop/data/goods/15235...
3   벨지오이오소           모짜렐라 로그  ...                    덩어리째로 만나보는 생 모짜렐라의 신선함  https://img-cf.kurly.com/shop/data/goods/14890...
4      브리미         락토스프리 리코타  ...  풍미와 식감은 물론 영양까지 일반 치즈와 견줘도 손색없는 락토스프리 치즈  https://img-cf.kurly.com/shop/data/goods/14948...
..     ...               ...  ...                                       ...                                                ...
91     프리코         스모크 치즈 2종  ...                            훈연한 치즈의 그윽한 풍미  https://img-cf.kurly.com/shop/data/goods/15632...
92    암브로시   유기농 파르마지아노 레지아노  ...                         유기농 우유로 만든 정교한 풍미  https://img-cf.kurly.com/shop/data/goods/15589...
93    앙트르몽            에멘탈 치즈  ...                    이탈리아에서 만든 신선함을 그대로 간직한  https://img-cf.kurly.com/shop/data/goods/15111...
94    브레살렛           모짜렐라 카우  ...                         이탈리아에서 생산된 고소한 치즈  https://img-cf.kurly.com/shop/data/goods/15953...
95     란다나      저지 고다 머추어 치즈  ...                 고급 품종인 저지 소의 우유로 만든 고다 치즈  https://img-cf.kurly.com/shop/data/goods/15777...
'''

'''
### before_df ###
	name	country	matching	texture	types	category	price	content	img
0	[캐시밸리] 미국 전통 치즈 5종	미국	볶음밥,파스타,퐁듀	세미하드	자연치즈	모짜렐라	4,900원	일상 속 가볍게 즐기는 치즈	https://img-cf.kurly.com/shop/data/goods/15647...
1	[안젤로] 고르곤졸라 피칸테	이탈리아	피자, 파스타, 스테이크, 배, 무화과, 샐러리	세미하드치즈	자연치즈	블루치즈	7,600원	섹시한 이탈리아 대표 블루치즈	https://img-cf.kurly.com/shop/data/goods/15107...
2	[라 콘타디나] 버팔로 리코타	이탈리아	샐러드, 과일	후레쉬치즈	자연치즈	리코타	9,600원	디저트 대신 떠먹고 싶은 구름을 닮은 치즈	https://img-cf.kurly.com/shop/data/goods/15235...
3	[벨지오이오소] 모짜렐라 로그	미국	카프레제, 샌드위치, 샐러드, 피자	후레쉬치즈	자연치즈	모짜렐라	15,900원	덩어리째로 만나보는 생 모짜렐라의 신선함	https://img-cf.kurly.com/shop/data/goods/14890...
4	[브리미] 락토스프리 리코타	이탈리아	샐러드, 라자냐, 크로스티니, 키쉬, 치즈케이크	후레쉬치즈	자연치즈	리코타	8,900원	풍미와 식감은 물론 영양까지 일반 치즈와 견줘도 손색없는 락토스프리 치즈	https://img-cf.kurly.com/shop/data/goods/14948...
...	...	...	...	...	...	...	...	...	...
91	[프리코] 스모크 치즈 2종	네덜란드	간식,와인,햄버거	소프트치즈	자연치즈	스모크치즈	3,500원	훈연한 치즈의 그윽한 풍미	https://img-cf.kurly.com/shop/data/goods/15632...
92	[암브로시] 유기농 파르마지아노 레지아노	이탈리아	와인, 맥주, 파스타, 리소토	하드치즈	자연치즈	파르미지아노 레지아노	11,900원	유기농 우유로 만든 정교한 풍미	https://img-cf.kurly.com/shop/data/goods/15589...
93	[앙트르몽] 에멘탈 치즈	프랑스	퐁듀,피자,샌드위치	하드치즈	자연치즈	에멘탈	7,200원	이탈리아에서 만든 신선함을 그대로 간직한	https://img-cf.kurly.com/shop/data/goods/15111...
94	[브레살렛] 모짜렐라 카우	이탈리아	카프레제, 샌드위치, 발사믹식초	후레쉬치즈	자연치즈	모짜렐라	3,960원	이탈리아에서 생산된 고소한 치즈	https://img-cf.kurly.com/shop/data/goods/15953...
95	[란다나] 저지 고다 머추어 치즈	네덜란드	샌드위치, 토스트, 카나페, 와인, 맥주	세미하드치즈	자연치즈	고다	12,500원	고급 품종인 저지 소의 우유로 만든 고다 치즈	https://img-cf.kurly.com/shop/data/goods/15777...
'''